#!/usr/bin/env bash
# =============================================================================
#  setup-hub.sh — configure a Raspberry Pi (or any Debian box) as the incubator
#  fleet HUB: Mosquitto (MQTT broker) + dnsmasq (friendly DNS names per unit).
#
#  The hub gives every unit a stable, human name (incubator1.<domain>, …) and a
#  single MQTT broker the units publish telemetry to / take commands from. It is
#  the LAN aggregation point; remote access is fronted separately by your
#  domain/reverse-proxy.
#
#  Usage:
#    sudo DNS_DOMAIN=incubator.lan ./hub/setup-hub.sh [units.csv]
#
#  Env:
#    DNS_DOMAIN   Friendly domain suffix (default: incubator.lan).
#    HUB_IP       This hub's LAN IP (default: auto-detected).
#    DHCP_RANGE   e.g. "192.168.1.100,192.168.1.150,12h" — set ONLY if you want
#                 dnsmasq to also be the LAN DHCP server and hand out the
#                 reserved IPs by MAC. Leave unset to do DNS-only (recommended
#                 unless you're replacing your router's DHCP).
#  Arg:
#    units.csv    Roster of <mac>,<name>,<ip> (default: hub/units.csv, else the
#                 bundled units.example.csv).
# =============================================================================
set -euo pipefail

DNS_DOMAIN="${DNS_DOMAIN:-incubator.lan}"
HUB_DIR="$(cd "$(dirname "$0")" && pwd)"
UNITS_CSV="${1:-${HUB_DIR}/units.csv}"
[[ -f "${UNITS_CSV}" ]] || UNITS_CSV="${HUB_DIR}/units.example.csv"
DNSMASQ_CONF="/etc/dnsmasq.d/incubator.conf"
MOSQ_CONF="/etc/mosquitto/conf.d/incubator.conf"

info() { echo -e "\033[0;32m[HUB]\033[0m $*"; }
warn() { echo -e "\033[1;33m[HUB]\033[0m $*"; }
die()  { echo -e "\033[0;31m[HUB]\033[0m $*" >&2; exit 1; }

[[ "$(id -u)" -eq 0 ]] || die "Run as root: sudo $0"

[[ "${DNS_DOMAIN}" =~ ^[a-zA-Z0-9.-]+$ ]] || die "Invalid DNS_DOMAIN: ${DNS_DOMAIN}"

HUB_IP="${HUB_IP:-$(hostname -I | awk '{print $1}')}"
[[ -n "${HUB_IP}" ]] || die "Could not determine HUB_IP — set it explicitly."

info "Domain: ${DNS_DOMAIN}  Hub IP: ${HUB_IP}  Units: ${UNITS_CSV}"

# ── Packages ────────────────────────────────────────────────────────────────
if command -v apt-get >/dev/null 2>&1; then
    info "Installing mosquitto + dnsmasq..."
    apt-get update -qq
    apt-get install -y --no-install-recommends mosquitto mosquitto-clients dnsmasq \
        || die "Package install failed."
else
    warn "apt-get not found — install mosquitto + dnsmasq manually."
fi

# ── Mosquitto broker ────────────────────────────────────────────────────────
install -D -m 0644 "${HUB_DIR}/mosquitto-incubator.conf" "${MOSQ_CONF}"
info "Mosquitto config → ${MOSQ_CONF}"

# ── dnsmasq: friendly names (+ optional DHCP reservations) ──────────────────
{
    echo "# Generated by hub/setup-hub.sh — incubator fleet naming"
    echo "domain=${DNS_DOMAIN}"
    echo "local=/${DNS_DOMAIN}/"
    echo "expand-hosts"
    echo "host-record=hub.${DNS_DOMAIN},${HUB_IP}"
    if [[ -n "${DHCP_RANGE:-}" ]]; then
        echo "dhcp-range=${DHCP_RANGE}"
    fi
    # One record per unit. host-record gives DNS; dhcp-host pins the IP by MAC
    # when this hub is also the DHCP server.
    while IFS=, read -r mac name ip; do
        mac="$(echo "${mac}" | tr -d '[:space:]')"
        name="$(echo "${name}" | tr -d '[:space:]')"
        ip="$(echo "${ip}" | tr -d '[:space:]')"
        [[ -z "${mac}" || "${mac}" == \#* ]] && continue
        [[ -z "${name}" || -z "${ip}" ]] && { warn "skipping malformed row: ${mac},${name},${ip}"; continue; }
        echo "host-record=${name}.${DNS_DOMAIN},${ip}"
        if [[ -n "${DHCP_RANGE:-}" ]]; then
            echo "dhcp-host=${mac},${name},${ip}"
        fi
    done < "${UNITS_CSV}"
} > "${DNSMASQ_CONF}"
info "dnsmasq config → ${DNSMASQ_CONF}"
grep -c '^host-record=.*incubator' "${DNSMASQ_CONF}" >/dev/null && \
    info "Named $(grep -c '^host-record' "${DNSMASQ_CONF}") host record(s)."

# ── Enable + (re)start ──────────────────────────────────────────────────────
if command -v systemctl >/dev/null 2>&1; then
    systemctl enable mosquitto dnsmasq >/dev/null 2>&1 || true
    systemctl restart mosquitto || warn "mosquitto restart failed — check: journalctl -u mosquitto"
    if ! systemctl restart dnsmasq; then
        warn "dnsmasq restart failed (often port 53 already in use by systemd-resolved)."
        warn "Fix: disable the stub resolver — see hub/README.md — then re-run."
    fi
fi

info "Hub ready. Point units at this broker:  MQTT_ENABLED=true MQTT_HOST=${HUB_IP}"
info "Verify a name once a unit is up:  getent hosts incubator1.${DNS_DOMAIN}"
